<a href="https://colab.research.google.com/github/Saisathwika-08/Generative-AI/blob/main/2303A52204_week8_ASS(8_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) esign a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library

In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
data = pd.read_csv("/content/winequality-red.csv")

In [6]:
X = data.drop("quality", axis=1)
y = data["quality"]

In [7]:
y = pd.cut(y, bins=[0, 5, 6, 10], labels=[0, 1, 2])



y = pd.get_dummies(y)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



model = keras.Sequential([
    keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(25, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(y.shape[1], activation='softmax')  # Output layer
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


2) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score

In [8]:
model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])



history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - accuracy: 0.3238 - loss: 1.1193 - val_accuracy: 0.3219 - val_loss: 1.1096
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3571 - loss: 1.1162 - val_accuracy: 0.3219 - val_loss: 1.1094
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3259 - loss: 1.1208 - val_accuracy: 0.3219 - val_loss: 1.1091
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3650 - loss: 1.1109 - val_accuracy: 0.3219 - val_loss: 1.1089
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3515 - loss: 1.1155 - val_accuracy: 0.3219 - val_loss: 1.1086
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3333 - loss: 1.1147 - val_accuracy: 0.3219 - val_loss: 1.1083
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3507 - loss: 1.1109 - val_accuracy: 0.3219 - val_loss: 1.1080
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3323 - loss: 1.1186 - val_accuracy: 0.3219 

In [10]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy}")


y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test.values, axis=1)




conf_matrix = confusion_matrix(y_true, y_pred_classes)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_true, y_pred_classes))

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3381 - loss: 1.0879  
Test Accuracy: 0.375
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step  
Confusion Matrix:
 [[34 79 28]
 [35 74 23]
 [15 20 12]]
Classification Report:
               precision    recall  f1-score   support

           0       0.40      0.24      0.30       141
           1       0.43      0.56      0.49       132
           2       0.19      0.26      0.22        47

    accuracy                           0.38       320
   macro avg       0.34      0.35      0.34       320
weighted avg       0.38      0.38      0.37       320



3) Build the application by loading the saved ANN model.
Tabela 1: ANN Architecture
Layer Neurons Activation Function
Hidden Layer - 1 16 relu
Hidden Layer - 2 20 relu
Hidden Layer - 3 25 relu
Hidden Layer - 4 10 relu
Tabela 2: Training Parameters
epochs batch size error metric Optimizer
100 64 accuracy adadelta
Dataset: https://drive.google.com/file/d/1uutPAkOSYb2Uror1mk2dZUtoYbCgz6DO/view?
usp=drive_link



In [11]:
model.save("wine_quality_model.h5")

In [12]:
def load_model():
    loaded_model = keras.models.load_model("wine_quality_model.h5")
    return loaded_model



loaded_model = load_model()
predictions = loaded_model.predict(X_test[:5])
print("Sample Predictions:", np.argmax(predictions, axis=1))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 495ms/step
Sample Predictions: [0 1 0 1 1]
